# This is a basic workflow to help you get started with Actions

name: Create Zip Release On Tag Push
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'Modernity-NomiCEu-${{ github.ref_name }}.zip'
          exclusions: >
            *.git*
      - name: Generate Changelog
        id: changelog
        uses: requarks/changelog-action@v1.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          includeInvalidCommits: true
          reverseOrder: true
          excludeTypes: ''
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "Modernity-NomiCEu-${{ github.ref_name }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.changelog.outputs.changes }}
          allowUpdates: true
          removeArtifacts: true
